-- Seeded from src/data/round.ts, the committed fixture.
INSERT INTO round (id, round_number, total_rounds, team_a_name, team_a_country, team_b_name, team_b_country, updated_at) VALUES (1, 3, 6, 'England', 'england', 'Italy', 'italy', datetime('now'));
INSERT INTO board (board_no, a_naf_name, a_naf_number, a_race, a_score, a_injuries, a_vacant, b_naf_name, b_naf_number, b_race, b_score, b_injuries, b_vacant, half, outlook, tourplay_match_id) VALUES (1, 'Thulean', NULL, 'Human', 1, 1, 0, 'Menzogna', NULL, 'Necromantic Horror', 2, 2, 0, 1, -0.5, NULL);
INSERT INTO board (board_no, a_naf_name, a_naf_number, a_race, a_score, a_injuries, a_vacant, b_naf_name, b_naf_number, b_race, b_score, b_injuries, b_vacant, half, outlook, tourplay_match_id) VALUES (2, 'GreenskinPhil', NULL, 'Slann', 0, 2, 0, 'Serafino', NULL, 'Black Orc', 1, 0, 0, 1, -0.5, NULL);
INSERT INTO board (board_no, a_naf_name, a_naf_number, a_race, a_score, a_injuries, a_vacant, b_naf_name, b_naf_number, b_race, b_score, b_injuries, b_vacant, half, outlook, tourplay_match_id) VALUES (3, 'Kfoged', NULL, 'Dark Elf', 2, 0, 0, 'Barbossa', NULL, 'Norse', 0, 1, 0, 2, 1, NULL);
INSERT INTO board (board_no, a_naf_name, a_naf_number, a_race, a_score, a_injuries, a_vacant, b_naf_name, b_naf_number, b_race, b_score, b_injuries, b_vacant, half, outlook, tourplay_match_id) VALUES (4, 'Torquemada', NULL, 'Elven Union', 0, 2, 0, 'Dirold', NULL, 'Khorne', 0, 2, 0, 1, 0, NULL);
INSERT INTO board (board_no, a_naf_name, a_naf_number, a_race, a_score, a_injuries, a_vacant, b_naf_name, b_naf_number, b_race, b_score, b_injuries, b_vacant, half, outlook, tourplay_match_id) VALUES (5, 'Bashto', NULL, 'High Elf', 2, 0, 0, 'Liam', NULL, 'Elven Union', 1, 2, 0, 2, 0.5, NULL);
INSERT INTO board (board_no, a_naf_name, a_naf_number, a_race, a_score, a_injuries, a_vacant, b_naf_name, b_naf_number, b_race, b_score, b_injuries, b_vacant, half, outlook, tourplay_match_id) VALUES (6, 'PeteW', NULL, 'Black Orc', 2, 2, 0, 'Diomlord', NULL, 'Dwarf', 2, 2, 0, 2, 0, NULL);
INSERT INTO board (board_no, a_naf_name, a_naf_number, a_race, a_score, a_injuries, a_vacant, b_naf_name, b_naf_number, b_race, b_score, b_injuries, b_vacant, half, outlook, tourplay_match_id) VALUES (7, 'Geggster', NULL, 'Necromantic Horror', 2, 1, 0, 'Yena', NULL, 'Tomb Kings', 0, 2, 0, 1, 0.5, NULL);
INSERT INTO board (board_no, a_naf_name, a_naf_number, a_race, a_score, a_injuries, a_vacant, b_naf_name, b_naf_number, b_race, b_score, b_injuries, b_vacant, half, outlook, tourplay_match_id) VALUES (8, 'Pipey', NULL, 'Lizardmen', 2, 2, 0, 'PanicoBlack', NULL, 'Chaos Chosen', 3, 1, 0, 2, -1, NULL);
